---
abstract: 'maintenance scripts for perlmonks.org'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perlmonks-Maintenance
no_index:
  directory:
    - t
    - inc
requires:
  Class::Method::Modifiers: '0'
  Data::Dump: '0'
  Exporter: '5'
  File::Spec: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  Net::DNS: '0'
  POSIX: '0'
  perl: '5.008'
resources:
  repository: git://github.com/Corion/Perlmonks-Maintenance.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
